block-list-secret-scan: []
custom-tool-name: Checkov
directory:
  - .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
summary-position: top
