[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
annotated_tag = true

version_scheme = "semver2"
version = "0.0.1"
version_files = []

# Commitizen will keep the major version at zero
# Useful during the initial development stage of your project
major_version_zero = true

bump_message = "chore(release): $current_version â†’ $new_version [skip-ci]"
# Update changelog on bump is not working correctly
update_changelog_on_bump = false
pre_bump_hooks = [
  "terraform-docs --recursive=true --recursive-include-main=true --recursive-path=modules .",
  "terraform-docs --recursive=true --recursive-include-main=false --recursive-path=examples .",
]
post_bump_hooks = []

changelog_file = "CHANGELOG.md"
# Provide extra variables to the changelog template
extras.repository_url = "https://github.com/esaporski/tf-module-template"

# Provide custom changelog jinja template path relative to the current working directory
template = "docs/.CHANGELOG.md.j2"
